project:
  type: website
  output-dir: docs
website:
# favicon: "content/img/clidewo-favicon.png"
  title: "Dr. Marifer Rocha Arrangoiz"
  site-url: "https://drmariferrocha.com"
  repo-url: "https://github.com/edgarodriguez/marifer-rocha-arrangoiz-website"
  open-graph: true
  draft-mode: gone
  navbar:
    pinned: false
#    logo: "content/img/logo_yellow3.png"
    background: "#6AABD2"
    right:
      - href: blog.qmd   
      - text: Contact 
        href: contact.qmd        
  page-footer:
    background: "#6AABD2"
    left: © Copyright 2025 CC-BY-NC.
    right: Multi-lenguage thanks to [babelquarto](https://docs.ropensci.org/babelquarto/index.html) and [Joel Nitta Website](https://www.joelnitta.com)
#  google-analytics: "G-RG1R3XP26Q"
#  cookie-consent:
#    type: express
#    style: headline
#    palette: dark

format:
  html:
    theme: yeti
    css: marifer_theme.css
    toc: true
    code-overflow: scroll
    backgroundcolor: "#F2EDE2"
    smooth-scroll: true 
babelquarto:
  languagecodes:
  - name: es
    text: "Español"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['es']
title-es: Dr. Marifer Rocha Arrangoiz
description-es: Dr. Marifer Rocha Arrangoiz website
author-es: Dr. Marifer Rocha Arrangoiz
lang: en